version: '3'

services:
  newsnow:
    image: newsnow:latest
    container_name: newsnow
    restart: always
    ports:
      - '8002:4444'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Shanghai
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=newsnow_development
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - DISABLE_LOGIN=true
