version: '3'

services:
  newsnow:
    build:
      context: .
      dockerfile: Dockerfile
    image: newsnow:latest
    container_name: newsnow-server
    restart: always
    ports:
      - '8002:4444'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Shanghai
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=newsnow_development
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - DISABLE_LOGIN=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
  redis:
    image: redis:latest
    container_name: newsnow-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
